***********************************************************;
*  LESSON 4, PRACTICE 4                                   *;
*    a) Create a new column named SqMiles by multiplying  *;
*       Acres by .0015625.                                *;
*    b) Create a new column named Camping as the sum of   *;
*       OtherCamping, TentCampers, RVCampers, and         *;
*       BackcountryCampers.                               *;
*    c) Format SqMiles and Camping to include commas and  *;
*       zero decimal places.                              *;
*    d) Modify the KEEP statement to include the new      *;
*       columns. Run the program.                         *;
***********************************************************;
libname pg1 "/folders/myfolders/pg194_ue/EPG194/data";

data np_summary_update;
	set pg1.np_summary;
	keep Reg ParkName DayVisits OtherLodging Acres SqMiles Camping;	
	*Add assignment statements;
	SqMiles = Acres *.0015625;
	Camping = otherCamping + TentCampers + RVCampers + BackCountryCampers;
	* or using     Camping=sum(OtherCamping,TentCampers, RVCampers,BackcountryCampers);
	format SqMiles Camping comma8.;
run;
